### ISSUE TITLE
Snap is several releases behind

### ISSUE THREAD

**Issue by TheKorn2** [giaever-online-iot/zwave-js-ui#10]
Latest/edge is stuck on 9.8.2 (2024-02-04), should be 9.9.0 (2024-02-15).

Latest/candidate also 9.8.2 (should be 9.8.3 or possibly 9.9.0, unclear from "releases in latest")

Latest/stable is on 9.7.1 (OK).

**Comment by robertsLando** [comment]
New version is coming

**Comment by TheKorn2** [comment]
@robertsLando Didn't know you were maintaining the snap! Figured it was a Canonical script that got stuck and needed some attention.  ;)

**Comment by robertsLando** [comment]
@TheKorn2 I'm not, @jmgiaever it's the author and main maintainer, I just help him sometimes when I can :)
