### ISSUE TITLE
Revision 374: libatomic.so.1 error

### ISSUE THREAD

**Issue by KBerstene** [giaever-online-iot/zwave-js-ui#13]
The issue from #8 appears to have returned:

`2024-05-28T11:52:07-04:00 zwave-js-ui.zwave-js-ui[1604]: node: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory`

I am currently on revision 374:

```
Name         Version  Rev  Tracking     Publisher       Notes
zwave-js-ui  v9.12.0  367  latest/edge  giaever-online  disabled
zwave-js-ui  v9.12.0  374  latest/edge  giaever-online  -
```

Using `sudo snap revert zwave-js-ui` to revert to revision 367 got me working again for now.

**Comment by jmgiaever** [comment]
Thanks,

Seems to only affect `armhf`. I've staged it. Should be a new release available in 30 minutes ish

**Comment by KBerstene** [comment]
Dang, sorry for not providing my architecture.  Will do next time.

Nice job pinpointing the issue, and thanks for the amazingly fast response!

**Comment by KBerstene** [comment]
Confirmed that revision 378 is working. Thanks!

**Comment by jmgiaever** [comment]
Released. Please give it a try!
