### ISSUE TITLE
Home assistant requires Zwave-JS-UI 9.14.4

### ISSUE THREAD

**Issue by dajomas** [giaever-online-iot/zwave-js-ui#14]
Hi there,

in snap, the current stable version is 9.13.4 but Home Assistant requires version 9.14.x which is (aside from snap) already stable. Can you please bump the candidate version to stable so it will work with the current stable version of Home Assistant (2024.7.1)?

Thanx.

**Comment by jimbudarz** [comment]
If you'd like a workaround, you may be able to use the candidate version of zwave-js-ui by switching channels of your zwave-js-ui installation:
```
snap switch zwave-js-ui --channel=latest/candidate
snap refresh
``` 

This worked for me (but my zwave server is running on a raspberry pi separate from my home assistant installation.)

**Comment by jmgiaever** [comment]
Hi. I'm the maintainer of the snap. I recommend using the channels which include specific versions. 

E.g `v9.14`. Using these channels will prevent ZUI/ZWJS to update beyond other SW requirements, and you better control in regards to upgrades between technology. 

Switch to it with

```
sudo snap switch zwave-js-ui --channel=v9.14/latest 
sudo snap refresh 
```

This will keep you on this version until you decide to upgrade.

**Comment by jmgiaever** [comment]
PS! `latest/stable` will always include the **stable** version. For a version to become stable it require it to reach the latest patch for that version, and by this definition `v9.13.x` is `latest/stable`.

**Comment by InterferencePattern** [comment]
> PS! `latest/stable` will always include the **stable** version. For a version to become stable it require it to reach the latest patch for that version, and by this definition `v9.13.4` is `latest/stable` for now.

If I understand correctly, the upstream **zwave-js-ui** doesn't define a "stable" version, so you define the Snap `stable` tag as "most recent minor version minus one, but with all available bug fixes".

So in this case the latest release of the upstream project is 9.14.4, so the Snap "stable" version will be 9.13.x until there's another minor feature bump and the upstream project releases 9.15.0. Only then will 9.14.x become "stable".

**Comment by jmgiaever** [comment]
How the channels are used is as I said, and it's not related to the upstream project. 

But the main reason for doing it like this, is to prevent unnecessary interruptions for those who are on the `latest/stable` channel. This decision was taken before Ubuntu let maintainers crate channels themselves, and at the moment we'll stick with this decision. 

Those who want to be on rolling releases must be on the candidate channel. 

Hopefully most users will start facilitating the tracks for each version, and do the updates themselves when necessary. And then it's possible to reconsider how releases are published. But not now.
