### ISSUE TITLE
Snapcraft package release is not updating with the latest versions 

### ISSUE THREAD

**Issue by jfhautenauven** [giaever-online-iot/zwave-js-ui#26]
Describe the bug
Hello, seems that the snapcraft repo is not updating with the latest versions of the package. Currently still on version 9.23 where the current code version is 9.26

To Reproduce
Snap refresh, no new package found

Expected behavior
Package is published correctly to Snapcraft and I can update to the latest available version

**Comment by robertsLando** [comment]
There was a problem with renoveatebot.json config as @jmgiaever changed the string delimiter in latest commits and the regex used to fetch the version failed. Fixed now and bumped :)

**Comment by jfhautenauven** [comment]
Thanks for the quick fix @robertsLando . 🥳
