### ISSUE TITLE
Snap version with renovatebot

### ISSUE THREAD

**Issue by Caelion** [giaever-online-iot/zwave-js-ui#29]
Hello
Maybe my question is stupid and i'm sorry if it's.

I have read other post about snap version difference versus main project zwave-js-ui and on the last topic the mention of renovatebot (https://github.com/giaever-online-iot/zwave-js-ui/issues/26).
I read that there waş a problem that is corrected.
On the main page, i see the renovatebot committed the new version (9.26 currently) :
![image](https://github.com/user-attachments/assets/56469e5c-dc70-4d19-a57a-6a4c473a453e)
But on snap website :
![image](https://github.com/user-attachments/assets/94582bf0-1819-4893-b6e6-a6f765aef302)
and on ssh with command `snap info zwave-js-ui` :
![image](https://github.com/user-attachments/assets/a44171dc-dd24-4ab5-b954-25bbab193a1c)
we don't see the new version ?

Do we have to continue to use latest channels ?

Regards for your advices

**Comment by robertsLando** [comment]
Thanks for your issue @Caelion , seems that for some unknown reason the build has failed on snap side, I have just triggered a new build now, let me know if it gets published correctly usually takes 10 minutes so for 9:40 AM (CET) it should be ready.

**Comment by robertsLando** [comment]
@Caelion Because of last issue with renovate bot the v9.25 has been skipped, that's why you don't see it in that way, starting from next zui release everything should be consistent :)

**Comment by jmgiaever** [comment]
I've made the tracks and updated latest. However I placed .24 and .25 in latest, just to make sure everyone get that update first before pushing .26 in case there are any upgrades that needs to be taken care of between versions.
