### ISSUE TITLE
15 Dec Update (9.5.1) breaks zwave-js-ui  on Raspbian 11

### ISSUE THREAD

**Issue by chrestme** [giaever-online-iot/zwave-js-ui#8]
Server fails to start after today's update on the latest/stable channel. Running on a RPi 4, with Raspbian 11. 

2023-12-15T22:49:39Z zwave-js-ui.zwave-js-ui[25626]: node: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
2023-12-15T22:49:39Z systemd[1]: snap.zwave-js-ui.zwave-js-ui.service: Main process exited, code=exited, status=127/n/a
2023-12-15T22:49:39Z systemd[1]: snap.zwave-js-ui.zwave-js-ui.service: Failed with result 'exit-code'.
2023-12-15T22:49:39Z systemd[1]: snap.zwave-js-ui.zwave-js-ui.service: Scheduled restart job, restart counter is at 3.
2023-12-15T22:49:39Z systemd[1]: Stopped Service for snap application zwave-js-ui.zwave-js-ui.
2023-12-15T22:49:39Z systemd[1]: snap.zwave-js-ui.zwave-js-ui.service: Start request repeated too quickly.
2023-12-15T22:49:39Z systemd[1]: snap.zwave-js-ui.zwave-js-ui.service: Failed with result 'exit-code'.
2023-12-15T22:49:39Z systemd[1]: Failed to start Service for snap application zwave-js-ui.zwave-js-ui.

I got this error a few weeks ago, but was able to fix by changing channel to latest/candidate, until that broke, and then I was able to fix by switching back to latest/stable.

**Comment by joey7855** [comment]
I've got the same issue. Seems this is related to #7 as I'm getting the same libatomic error. I tried going to latest/candidate and latest/edge and both have this issue so I'm unable to use zwave-js-ui entirely.

**Comment by skywalker1979** [comment]
same here....i'm screwed...i changed from stable to candidate..but it's dead. 😢

**Comment by jeepasaurus** [comment]
Same problem here. The snap automatically updated around 2PM today and that's when it quit working. Running latest/stable on Raspbian 11 on a RPi2.

Decided to revert to previous version, which is working just fine. First listed the versions available
`sudo snap list zwave-js-ui --all`

It returned
```bash
Name         Version  Rev  Tracking       Publisher       Notes
zwave-js-ui  v9.4.1   287  latest/stable  giaever-online  disabled
zwave-js-ui  v9.5.1   304  latest/stable  giaever-online  -
```
I had a previous version available (rev 287). Issued the following command
`sudo snap revert zwave-js-ui`

Checked the logs
`sudo snap logs zwave-js-ui`

And Bob's yer uncle. Back in business!

**Comment by robertsLando** [comment]
Cc @jmgiaever

**Comment by skywalker1979** [comment]
i managed to restore the situation by going back as well to 287.

**Comment by nobleIntent** [comment]
> i managed to restore the situation by going back as well to 287.

Thank you for posting this fix, reverting back fixed me as well.

**Comment by Koektrommel82** [comment]
Thanks a lot for posting this, it took me quite some time and effort to figure out why I could no longer access the zwave-js-ui web interface. Reverting fixed the issue

**Comment by jmgiaever** [comment]
Hi,

I will again try to fix it and build and publish new builds, but please take the effort to report back within reasonable time, and don't stay silent as @rglory did in the #7 issue. 

I just took it for granted that the issue got fixed, since he never got back to me. 

This is mainly an issue with Rasbian only and not with Ubuntu (neither Server or Core editions). I don't use Rasbian and can't debug or confirm fixes.

**Comment by jmgiaever** [comment]
New builds are out in `stable` (v9.5.1)

**Comment by nobleIntent** [comment]
> New builds are out in `stable` (v9.5.1)

ran sudo snap refresh zwave-jus-ui
Verison 9.5.1 is working on my Raspberry Pi
Thank you!

**Comment by Koektrommel82** [comment]
Pls don't hesitate to drop me an email when needed. I am not an expert on Rasbian, but will do my best to help.

**Comment by Koektrommel82** [comment]
ran sudo snap refresh zwave-js-ui --channel=latest/edge and version 9.5.1 is working on my Raspberry Pi as well


    On Saturday, December 16, 2023 at 08:44:27 PM GMT+1, nobleIntent ***@***.***> wrote:  
 
 



New builds are out in stable (v9.5.1)


ran sudo snap refresh zwave-jus-ui
Verison 9.5.1 is working on my Raspberry Pi
Thank you!

**Comment by rglory** [comment]
> I will (again) try to fix it, build it and publish new builds. But **please** take the effort to report back within reasonable time, and don't stay silent as @rglory did in the #7 issue.

Sorry I did not test in time, problem is my system is in use, just to test it I either need to break my home automation or find a new pi and install it there from scratch, neither is very practical.

**Comment by jmgiaever** [comment]
>  ran sudo snap refresh zwave-js-ui --channel=latest/edge and version 9.5.1 is working on my Raspberry Pi as well

Great, but I don't recommend using the edge channel. Use stable or candidate instead. There's a description on how I facilitate them in the snap package description:

```
snap info zwave-js-ui
```

**Comment by jmgiaever** [comment]
> Sorry I did not test in time, problem is my system is in use, just to test it I either need to break my home automation or find a new pi and install it there from scratch, neither is very practical.

Ok. Thanks for letting me know. In the future it would be great if these things are shared with me, so I know. 

I'm doing this in my free time and I'm the only maintener. My devices are all running Ubuntu Server or Core editions, which is the "targeted" OS for snaps, so I only have the option to test with them. And this bug didn't happen there. 

(Since this is a hobby project for me I'm not spending any on my own money to make a test environment. If anyone is interested to donate devices for testing it's highly appreciated).

**Comment by joey7855** [comment]
Everything is working on my end with the update today. Thank you @jmgiaever !

**Comment by chrestme** [comment]
Thanks! Today's update fixed the issue. I think I just need to configure snap to not automatically update this particular package so I can verify any updates won't break my system.

Thanks for the quick turn around and maintaining!

**Comment by Koektrommel82** [comment]
Thanks, changed to stable and still working :-)

**Comment by jeepasaurus** [comment]
Looks like the snap auto updated to rev 314 and it's all good! Thanks for the quick turn around @jmgiaever !!!

**Comment by automaton82** [comment]
Hey thanks for the quick fix on this. This bit me as well on Raspbian 11 while I was away from home (of course...) and had to revert.

Just did the `unhold` now and upgraded to rev 314 and all is good.

**Comment by rglory** [comment]
I do not really like default behavior of snap - it is updating automatically. I am using home automation for water leak detection for example and realizing that my system is dysfunctional due to automatic update later is quite disturbing. Home Assistant is made properly in that sense - it reminds you that there are updates but does not do it by itself. When I do it manually - I would check that everything works after update.
